#!/bin/bash

APP_NAME=Eiffel
EIFFEL_USER=eiffel

FASTCGI_BIN=/app/bin/app.fcgi
FASTCGI_BIND=0.0.0.0:9000
FASTCGI_ARGS="- ${FASTCGI_BIN} -b ${FASTCGI_BIND}"
RETVAL=0

start() {
	echo -n "Starting ${APP_NAME} FastCGI: "
	start-stop-daemon \
		--start \
		--background \
		--user ${EIFFEL_USER} \
		--output /dev/stdout \
		--exec /usr/bin/env -- \
		${FASTCGI_ARGS}
	RETVAL=$?
	echo "started."
}

stop() {
	echo -n "Stopping ${APP_NAME} FastCGI: "
	echo -n "Stopping ${APP_NAME} application: "
	start-stop-daemon \
		--stop \
		--user ${APP_USER} \
		--name ${APP_NAME} \
		--exec ${APP_BIN} \
		--pidfile ${APP_PID}
	RETVAL=$?
	echo "stoped."
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
		restart)
		stop
		start
	;;
	*)
	echo "Usage: app {start|stop|restart}"
	exit 1
	;;
esac
exit ${RETVAL}
