#!/bin/bash

APP_NAME=Eiffel
EIFFEL_USER=eiffel

FASTCGI_BIN=/app/bin/app.fcgi
FASTCGI_PID=/var/run/app.pid
FASTCGI_LOG=/var/log/app.log
FASTCGI_BIND=tcp:0.0.0.0:9000
FASTCGI_ARGS="-f -c 1 -s ${FASTCGI_BIND} -p ${FASTCGI_BIN}"
RETVAL=0

start() {
	echo -n "Starting FastCGI ${APP_NAME}: "
	start-stop-daemon \
		--start \
		--background \
		--user ${EIFFEL_USER} \
		--make-pidfile \
		--pidfile ${FASTCGI_PID} \
		--output ${FASTCGI_LOG} \
		--exec /usr/sbin/fcgiwrap -- \
		${FASTCGI_ARGS}
	RETVAL=$?
	echo "started."
}

stop() {
	echo -n "Stopping FastCGI ${APP_NAME}: "
	start-stop-daemon \
		--stop \
		--user ${EIFFEL_USER} \
		--remove-pidfile \
		--pidfile ${FASTCGI_PID}
	RETVAL=$?
	echo "stopped."
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
		restart)
		stop
		start
	;;
	*)
	echo "Usage: app {start|stop|restart}"
	exit 1
	;;
esac
exit ${RETVAL}
