#!/bin/bash

APP_USER=nginx
APP_NAME=nginx
APP_BIN=/usr/sbin/${APP_NAME}
APP_PID=/var/run/${APP_NAME}.pid
RETVAL=0

start() {
	echo -n "Starting ${APP_NAME} application: "
	start-stop-daemon --quiet --start --background \
		--user $APP_USER \
		--name $APP_NAME \
		--exec $APP_BIN \
		--pidfile $APP_PID
	RETVAL=$?
	echo "started."
}

stop() {
	echo -n "Stopping ${APP_NAME} application: "
	killall -q -w -u $APP_USER $APP_BIN
	RETVAL=$?
	echo "stopped."
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		stop
		start
	;;
	*)
	echo "Usage: ${APP_NAME} {start|stop|restart}"
	exit 1
	;;
esac
exit $RETVAL
