#!/bin/bash

NGINX_USER=nginx
NGINX_NAME=nginx
NGINX_BIN=/usr/sbin/${NGINX_NAME}
NGINX_PID=/var/run/${NGINX_NAME}.pid
RETVAL=0

start() {
	echo -n "Starting ${NGINX_NAME} application: "
	start-stop-daemon \
		--start \
		--user ${NGINX_USER} \
		--name ${NGINX_NAME} \
		--exec ${NGINX_BIN} \
		--pidfile ${NGINX_PID}
	RETVAL=$?
	echo "started."
}

stop() {
	echo -n "Stopping ${NGINX_NAME} application: "
	start-stop-daemon \
		--stop \
		--user ${NGINX_USER} \
		--name ${NGINX_NAME} \
		--exec ${NGINX_BIN} \
		--pidfile ${NGINX_PID}
	RETVAL=$?
	echo "stopped."
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)
		stop
		start
	;;
	*)
	echo "Usage: ${NGINX_NAME} {start|stop|restart}"
	exit 1
	;;
esac
exit ${RETVAL}
