name: Build and Push all applications to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci-${{ github.ref }}
    strategy:
      matrix:
        applications:
          - name: ruby
            build-flags: --build-arg RUBY_ARCHITECTURE=linux

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Display current tool's versions
        run: |
          echo "aws: `aws --version`"
          echo "jq: `jq --version`"
          echo "node: `node --version`"
          echo "npm: `npm --version`"
          echo "docker: `docker --version`"
          echo "ruby: `ruby --version`"

      - name: Get short SHA and tag
        id: get-short-sha-and-tag
        run: |
          echo "::set-output name=sha::`echo ${{ github.sha }} | cut -b 1-7`"
          echo "::aet-output name=tag::`echo ${{ steps.bump-version.outputs.new_tag }} | awk -F '-' '{ print $1 }'`"

      - name: Build environment map
        id: build-environment-json
        run: |
          echo "::set-output name=map::`echo '{\"environments\":{\"main\":\"production\",\"dev\":\"development\"}}'`"

      - name: Get environment json map
        run: |
          echo "${{ steps.build-environment-json.outputs.map }}"

      - name: Get environment branch
        id: get-current
        run: |
          echo "::set-output name=branch::${{github.ref_name}}"

      - name: Get environment name based on map
        id: get-environment
        run: |
          echo "::set-output name=name::`echo '${{ steps.build-environment-json.outputs.map }}' | jq -r .environments.${{ steps.get-current.outputs.branch }}`"

      - name: Generate version for every container
        run: |
          cat <<EOF > version.json
          {
            "sha": "${{ steps.get-short-sha-and-tag.outputs.sha }}",
            "tag": "${{ steps.get-short-sha-and-tag.outputs.tag }}",
            "env": "${{ steps.get-environment.outputs.name }}",
            "branch": "${{ steps.get-current.outputs.branch }}"
          }
          cp version.json ruby/app python/app

      - name: Use hadolint to sanitize Ruby Dockerfile
        run: |
          docker pull hadolint/hadolint
          set -xe
          echo "Checking Ruby..."
          docker container run --rm -i hadolint/hadolint hadolint "$@" - < ruby/Dockerfile
          echo "Checking Python..."
          docker container run --rm -i hadolint/hadolint hadolint "$@" - < python/Dockerfile

#     - name: Run Snyk to check for Docker vulnerabilities
#       uses: snyk/actions/ruby@master
#       env:
#         SNYK_TOKEN: ${{ secrets.MPC_SNYK_AUTH_TOKEN }}
#       with:
#         args: --target-dir ./ruby

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.MPC_DOCKER_USERNAME }}
          password: ${{ secrets.MPC_DOCKER_PERSONAL_TOKEN }}

      - name: Build and push Ruby image to DockerHub
        uses: docker/build-push-action@v3
        with:
          build-args: |
            RUBY_ARCHITECTURE=linux
          build-contexts: |
            project=./ruby .
          tags: |
            name: ${{ secrets.MPC_DOCKER_USERNAME }}/thall-ruby:latest
          push: true

      - name: Build and push Python image to DockerHub
        uses: docker/build-push-action@v3
        with:
          build-contexts: |
            --build-context name=./python .
          tags: |
            name: ${{ secrets.MPC_DOCKER_USERNAME }}/thall-python:latest
          push: true

